import json
from datetime import datetime, timezone
from pathlib import Path

import duckdb
import polars as pl

PERF_PATH = Path("results/performance.json")
MODEL_META_PATH = Path("model/metadata.json")
LEADERBOARD_DIR = Path("data/leaderboard")
README_PATH = Path("README.md")

_STRATEGIES = pl.DataFrame({
    "profile_name": ["Random Randy", "Boomer Bob", "Momentum Mike", "Reddit Rita", "Claude", "Rick RF"],
    "strategy":     ["random",       "blue_chip",  "momentum",      "wsb_sentiment", "llm_news", "random_forest"],
})


def _md_table(df: pl.DataFrame) -> str:
    cols = df.columns
    lines = [
        "| " + " | ".join(cols) + " |",
        "| " + " | ".join(["---"] * len(cols)) + " |",
    ]
    for row in df.iter_rows():
        lines.append("| " + " | ".join("" if v is None else str(v) for v in row) + " |")
    return "\n".join(lines)


def _pct(v: float) -> str:
    return f"{v:+.1f}%"


def load_performance() -> pl.DataFrame:
    data = json.loads(PERF_PATH.read_text())
    return pl.DataFrame([{"profile_name": k, **v} for k, v in data.items()])


def write_leaderboard(perf: pl.DataFrame, year: int, week: int) -> pl.DataFrame:
    ranked = (
        perf.with_columns(
            pl.col("return_pct").rank(method="ordinal", descending=True).cast(pl.Int32).alias("rank")
        )
        .sort("rank")
        .select(["rank", "profile_name", "return_pct", "vs_sp500", "wins", "losses"])
        .with_columns([pl.lit(year).alias("year"), pl.lit(week).alias("week")])
    )
    out_path = LEADERBOARD_DIR / f"year={year}" / f"week={week}.parquet"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    ranked.write_parquet(out_path, compression="snappy")
    return ranked


def leaderboard_section(ranked: pl.DataFrame, perf: pl.DataFrame) -> str:
    display = (
        ranked.join(_STRATEGIES, on="profile_name", how="left")
        .join(perf.select(["profile_name", "best_pick"]), on="profile_name", how="left")
        .select([
            pl.col("rank").alias("Rank"),
            pl.col("profile_name").alias("Profile"),
            pl.col("strategy").alias("Strategy"),
            pl.col("return_pct").map_elements(_pct, return_dtype=pl.Utf8).alias("Return"),
            pl.col("vs_sp500").map_elements(_pct, return_dtype=pl.Utf8).alias("vs S&P 500"),
            pl.col("wins").alias("W"),
            pl.col("losses").alias("L"),
            pl.col("best_pick").alias("Best Pick"),
        ])
    )
    return _md_table(display)


def rank_progression_section(con: duckdb.DuckDBPyConnection) -> str:
    if not any(LEADERBOARD_DIR.glob("year=*/week=*.parquet")):
        return "_No rank history yet._"

    history = con.execute(
        "SELECT profile_name, year, week, rank "
        "FROM read_parquet('data/leaderboard/year=*/week=*.parquet', hive_partitioning=true) "
        "ORDER BY year, week"
    ).pl()

    pivot = (
        history.with_columns(
            pl.concat_str(
                [pl.col("year").cast(pl.Utf8), pl.lit("-W"), pl.col("week").cast(pl.Utf8).str.zfill(2)],
                separator="",
            ).alias("week_label")
        )
        .pivot(on="week_label", index="profile_name", values="rank", aggregate_function="first")
    )

    # Sort rows by latest week's rank; sort columns chronologically
    week_cols = sorted([c for c in pivot.columns if c != "profile_name"])
    if week_cols:
        pivot = pivot.sort(week_cols[-1], nulls_last=True)
    pivot = pivot.select(["profile_name"] + week_cols)

    return _md_table(pivot.rename({"profile_name": "Profile"}))


def model_health_section() -> str:
    if not MODEL_META_PATH.exists():
        return "_No model trained yet._"

    meta = json.loads(MODEL_META_PATH.read_text())
    table = _md_table(pl.DataFrame([
        {"Metric": "val_accuracy",    "Value": f"{meta['val_accuracy']:.4f}"},
        {"Metric": "val_f1",          "Value": f"{meta['val_f1']:.4f}"},
        {"Metric": "n_training_rows", "Value": str(meta["n_training_rows"])},
        {"Metric": "trained_at",      "Value": meta["trained_at"]},
    ]))
    features = ", ".join(f"`{f}`" for f in meta.get("feature_names", []))
    return table + f"\n\n**Features:** {features}"


def main() -> None:
    now = datetime.now(timezone.utc)
    iso = now.isocalendar()
    year, week = iso.year, iso.week
    timestamp = now.strftime("%Y-%m-%d %H:%M UTC")

    if not PERF_PATH.exists():
        README_PATH.write_text(
            f"# Stock Tournament — {year} W{week:02d}\n\n"
            f"> Auto-generated by `src/render.py` — do not edit manually.  \n"
            f"> Last updated: {timestamp}\n\n"
            f"_No performance data yet — waiting for the first week of picks to settle._\n",
            encoding="utf-8",
        )
        print("No performance data yet — wrote placeholder README.")
        return

    perf = load_performance()
    con = duckdb.connect()

    ranked = write_leaderboard(perf, year, week)

    readme = (
        f"# Stock Tournament — {year} W{week:02d}\n\n"
        f"> Auto-generated by `src/render.py` — do not edit manually.  \n"
        f"> Last updated: {timestamp}\n\n"
        f"## Leaderboard\n\n"
        f"{leaderboard_section(ranked, perf)}\n\n"
        f"## Rank Progression\n\n"
        f"{rank_progression_section(con)}\n\n"
        f"## Rick RF — Model Health\n\n"
        f"{model_health_section()}\n\n"
        f"## How It Works\n\n"
        f"Six profiles compete weekly to pick three stocks each from an 80-ticker S&P 500 universe "
        f"spanning tech, financials, healthcare, energy, and consumer staples. "
        f"Every Monday, each profile calls `pick()` and the selections are logged with entry prices. "
        f"After seven days, exit prices are fetched, returns are calculated, and the results feed a training set. "
        f"Rick RF is the only profile that learns — he trains a Random Forest classifier on accumulated outcomes "
        f"and improves his picks over time. "
        f"All data is stored as Snappy-compressed Parquet files partitioned by year and week; "
        f"the leaderboard and this README are regenerated automatically via GitHub Actions.\n"
    )

    README_PATH.write_text(readme, encoding="utf-8")
    print(f"README.md written — year={year} week={week}")
    for row in ranked.iter_rows(named=True):
        print(f"  #{row['rank']} {row['profile_name']}: {_pct(row['return_pct'])}")


if __name__ == "__main__":
    main()
